// TrainingOfficerCourses.tsx - COMPLETE WORKING VERSION WITH IMPROVED MOBILE RESPONSIVENESS
import React, { useState, useEffect } from 'react';
import { Search, Plus, Filter, Eye, Edit, Trash2, BookOpen, X, MapPin, Loader2, Users, User, AlertCircle, Building, Calendar, Clock, RefreshCw } from 'lucide-react';
import { type CourseType, fetchCourses, createCourse, updateCourse, deleteCourse, fetchInstructors, fetchUsers, fetchCourseCategories, fetchCourseDurations, fetchAvailableCourseCodes, type CourseCodeType } from '../../../api/cbt_api';
import { fetchCenters, type Center } from '../../../api/cbt_api';
import toast from 'react-hot-toast';

// Mock data removed

// Add Course Modal Component
interface AddCourseModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSave: (courseData: Partial<CourseType>) => Promise<void>;
  districts: string[];
  instructors: any[];
  centers: Center[];
  categories: string[];
  durations: string[];
  submitting: boolean;
  userDistrict?: string;
  instructorsError?: boolean;
  existingCourses: CourseType[];
}

const AddCourseModal: React.FC<AddCourseModalProps> = ({
  isOpen,
  onClose,
  onSave,
  districts,
  instructors,
  centers,
  categories,
  durations,
  submitting,
  userDistrict,
  instructorsError,
  existingCourses
}) => {
  const [formData, setFormData] = useState({
    name: '',
    code: '',
    category: '',
    duration: '',
    description: '',
    district: userDistrict || '',
    center: '',
    instructor: '',
    students: '0'
  });

  const [isAutoGenerated, setIsAutoGenerated] = useState(true);
  const [officialCourseCodes, setOfficialCourseCodes] = useState<CourseCodeType[]>([]);

  // Load course codes on mount
  useEffect(() => {
    const loadCodes = async () => {
      try {
        const cCodes = await fetchAvailableCourseCodes();
        setOfficialCourseCodes(cCodes);
      } catch (error) {
        console.error('Error loading codes:', error);
      }
    };
    if (isOpen) {
      loadCodes();
    }
  }, [isOpen]);

  // Filter instructors and centers by selected district
  // Filter instructors and centers by selected district
  // Filter instructors and centers by selected district
  const filteredInstructors = Array.isArray(instructors) ? instructors.filter(instructor => {
    if (!instructor.district) return false;
    if (!formData.district) return false;


    const normalize = (s: string) => s.toLowerCase().replace("district", "").trim();
    const d1 = normalize(instructor.district || "");
    const d2 = normalize(formData.district || "");

    // DEBUG LOG
    console.log(`Filtering Instructor: ${instructor.first_name} (${d1}) vs Selected (${d2}) -> Match: ${d1 === d2 || d1.includes(d2) || d2.includes(d1)}`);

    // Check for match after normalization
    return d1 === d2 || d1.includes(d2) || d2.includes(d1);
  }) : [];

  const filteredCenters = Array.isArray(centers) ? centers.filter(center =>
    center.district === formData.district
  ) : [];

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    // Validate required fields
    if (!formData.name.trim() || !formData.code.trim() || !formData.district.trim() || !formData.center.trim()) {
      toast.error('Please fill in all required fields (Name, Code, District, and Center)');
      return;
    }

    try {
      const courseToSave = {
        name: formData.name,
        code: formData.code,
        category: formData.category,
        duration: formData.duration,
        description: formData.description,
        district: formData.district,
        center: parseInt(formData.center),
        instructor: formData.instructor ? parseInt(formData.instructor) : null,
        students: parseInt(formData.students) || 0,
        progress: 0,
        status: 'Pending' as const,
        priority: 'Medium' as const,
      };
      await onSave(courseToSave);
      setFormData({
        name: '',
        code: '',
        category: '',
        duration: '',
        description: '',
        district: userDistrict || '',
        center: '',
        instructor: '',
        students: '0'
      });
      onClose();
    } catch (error) {
      console.error('Error saving course:', error);
    }
  };

  // Reset form when modal closes and auto-fill district
  useEffect(() => {
    if (isOpen) {
      setFormData(prev => ({
        ...prev,
        district: userDistrict || prev.district,
        center: '',
        instructor: ''
      }));
    } else {
      setFormData({
        name: '',
        code: '',
        category: '',
        duration: '',
        description: '',
        district: userDistrict || '',
        center: '',
        instructor: '',
        students: '0'
      });
    }
  }, [isOpen, userDistrict]);

  // Reset instructor and center selection when district changes
  useEffect(() => {
    if (isOpen) {
      setFormData(prev => ({
        ...prev,
        center: '',
        instructor: ''
      }));
    }
  }, [formData.district, isOpen]);

  // Auto-generate course code on open or when dependencies change
  useEffect(() => {
    if (isOpen && isAutoGenerated) {
      // Generate based on Name (e.g., 'Web Programming' -> 'WP')
      if (formData.name) {
        generateId();
      }
    }
  }, [isOpen, formData.name, isAutoGenerated, officialCourseCodes, existingCourses]);

  const generateId = () => {
    // 1. Get Course Name Acronym (e.g., 'WP' for 'Web Programming')
    let namePrefix = 'CRS';
    const cleanName = formData.name.trim();

    if (cleanName) {
      // Try to find official code first
      const foundCode = officialCourseCodes.find(c => c.course_name.toLowerCase() === cleanName.toLowerCase());
      if (foundCode) {
        namePrefix = foundCode.course_code;
      } else {
        // Generate Acronym: "Web Programming" -> "WP"
        // remove common stop words for better acronyms
        const words = cleanName.split(/\s+/).filter(w => w.length > 0 && !['and', 'of', 'in', 'for', 'the', '&'].includes(w.toLowerCase()));
        if (words.length > 0) {
          if (words.length === 1) {
            namePrefix = words[0].substring(0, 3).toUpperCase();
          } else {
            namePrefix = words.map(w => w[0]).join('').substring(0, 4).toUpperCase();
          }
        }
      }
    } else if (formData.category) {
      // Fallback to Category
      namePrefix = formData.category.substring(0, 3).toUpperCase();
    }

    // 2. Find next sequence number
    // Format: WP001 (Prefix + 3 digits)
    const prefix = namePrefix;
    let maxNum = 0;

    // Check existing courses for codes starting with this prefix followed by digits
    existingCourses.forEach(course => {
      if (course.code && course.code.startsWith(prefix)) {
        // user might have formats like WP001 or WP-001, handled flexibly?
        // User requested "WP001", so let's stick to that strict format for generation
        // But for parsing, we extract the numbers from the end
        const match = course.code.match(/(\d+)$/);
        if (match) {
          const numPart = parseInt(match[1]);
          if (!isNaN(numPart) && numPart > maxNum) {
            maxNum = numPart;
          }
        }
      }
    });

    const nextNum = (maxNum + 1).toString().padStart(3, '0');
    setFormData(prev => ({ ...prev, code: `${prefix}${nextNum}` }));
    setIsAutoGenerated(true);
  };

  const handleManualCodeChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setFormData({ ...formData, code: e.target.value.toUpperCase() });
    setIsAutoGenerated(false);
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black bg-opacity-50">
      <div className="bg-white rounded-xl shadow-2xl w-full max-w-lg sm:max-w-3xl p-5 sm:p-8 relative max-h-[90vh] overflow-y-auto">
        <button
          onClick={onClose}
          className="absolute top-3 sm:top-5 right-3 sm:right-5 text-gray-400 hover:text-gray-600"
        >
          <X className="w-5 sm:w-6 h-5 sm:h-6" />
        </button>

        <h2 className="text-xl sm:text-2xl font-bold text-gray-900 mb-6 sm:mb-8">Add New Course</h2>

        <form onSubmit={handleSubmit} className="grid grid-cols-1 sm:grid-cols-2 gap-5 sm:gap-6">
          <div className="sm:col-span-2">
            <label className="block text-sm font-medium text-gray-700 mb-1">
              Course Name <span className="text-red-500">*</span>
            </label>
            <input
              type="text"
              required
              value={formData.name}
              onChange={(e) => setFormData({ ...formData, name: e.target.value })}
              className="w-full px-3 sm:px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-green-500 focus:border-transparent"
              placeholder="Web Development Fundamentals"
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              Course Code <span className="text-red-500">*</span>
            </label>

            <div className="flex gap-2">
              <input
                type="text"
                required
                value={formData.code}
                onChange={handleManualCodeChange}
                className={`w-full px-3 sm:px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-green-500 focus:border-transparent ${isAutoGenerated ? 'bg-gray-50' : 'bg-white'}`}
                placeholder="WP001"
              />
              <button
                type="button"
                onClick={generateId}
                className="p-2 border border-gray-300 rounded-lg hover:bg-gray-50 text-gray-600"
                title="Generate New Code"
              >
                <RefreshCw className="w-5 h-5" />
              </button>
            </div>
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              Category
            </label>
            <select
              value={formData.category}
              onChange={(e) => setFormData({ ...formData, category: e.target.value })}
              className="w-full px-3 sm:px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-green-500 focus:border-transparent"
            >
              <option value="">Select Category</option>
              {categories.map((category) => (
                <option key={category} value={category}>{category}</option>
              ))}
            </select>
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              Duration
            </label>
            <select
              value={formData.duration}
              onChange={(e) => setFormData({ ...formData, duration: e.target.value })}
              className="w-full px-3 sm:px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-green-500 focus:border-transparent"
            >
              <option value="">Select Duration</option>
              {durations.map((duration) => (
                <option key={duration} value={duration}>{duration}</option>
              ))}
            </select>
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              <Users className="w-3 sm:w-4 h-3 sm:h-4 inline mr-1" />
              Student Count
            </label>
            <input
              type="number"
              min="0"
              value={formData.students}
              onChange={(e) => setFormData({ ...formData, students: e.target.value })}
              className="w-full px-3 sm:px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-green-500 focus:border-transparent"
              placeholder="0"
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              <Building className="w-3 sm:w-4 h-3 sm:h-4 inline mr-1" />
              Center <span className="text-red-500">*</span>
              {formData.district && (
                <span className="text-xs text-gray-500 ml-1">
                  (in {formData.district})
                </span>
              )}
            </label>
            <div className="relative">
              <Building className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 w-3 sm:w-4 h-3 sm:h-4" />
              <select
                required
                value={formData.center}
                onChange={(e) => setFormData({ ...formData, center: e.target.value })}
                className="w-full pl-8 sm:pl-10 pr-3 sm:pr-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-green-500 focus:border-transparent appearance-none"
                disabled={!formData.district}
              >
                <option value="">
                  {formData.district ? 'Select Center' : 'Select district first'}
                </option>
                {filteredCenters.map((center) => (
                  <option key={center.id} value={center.id}>
                    {center.name}
                    {center.location && ` - ${center.location}`}
                  </option>
                ))}
              </select>
              <div className="pointer-events-none absolute inset-y-0 right-0 flex items-center px-2 text-gray-700">
                <svg className="fill-current h-3 w-3 sm:h-4 sm:w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                  <path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z" />
                </svg>
              </div>
            </div>
            {formData.district && filteredCenters.length === 0 && (
              <p className="text-xs text-yellow-600 mt-1">
                No centers found in {formData.district} district
              </p>
            )}
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              <User className="w-3 sm:w-4 h-3 sm:h-4 inline mr-1" />
              Instructor {formData.district && (
                <span className="text-xs text-gray-500 ml-1">
                  (in {formData.district})
                </span>
              )}
            </label>
            <div className="relative">
              <User className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 w-3 sm:w-4 h-3 sm:h-4" />
              <select
                value={formData.instructor}
                onChange={(e) => setFormData({ ...formData, instructor: e.target.value })}
                className="w-full pl-8 sm:pl-10 pr-3 sm:pr-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-green-500 focus:border-transparent appearance-none"
                disabled={!formData.district || instructorsError}
              >
                <option value="">
                  {instructorsError ? 'Unable to load instructors' :
                    formData.district ? 'Select Instructor' : 'Select district first'}
                </option>
                {filteredInstructors.map((instructor) => (
                  <option key={instructor.id} value={instructor.id}>
                    {instructor.first_name} {instructor.last_name}
                    {instructor.email && ` (${instructor.email})`}
                  </option>
                ))}
              </select>
              <div className="pointer-events-none absolute inset-y-0 right-0 flex items-center px-2 text-gray-700">
                <svg className="fill-current h-3 w-3 sm:h-4 sm:w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                  <path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z" />
                </svg>
              </div>
            </div>
            {instructorsError && (
              <p className="text-xs text-red-600 mt-1 flex items-center">
                <AlertCircle className="w-3 sm:w-4 h-3 sm:h-4 mr-1" />
                Failed to load instructors. Please try again.
              </p>
            )}
            {formData.district && filteredInstructors.length === 0 && !instructorsError && (
              <p className="text-xs text-yellow-600 mt-1">
                No instructors found in {formData.district} district
              </p>
            )}
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              District <span className="text-red-500">*</span>
              {userDistrict && <span className="text-green-600 ml-2">(Auto-filled)</span>}
            </label>
            <div className="relative">
              <MapPin className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 w-3 sm:w-4 h-3 sm:h-4" />
              <select
                required
                value={formData.district}
                onChange={(e) => setFormData({ ...formData, district: e.target.value })}
                className="w-full pl-8 sm:pl-10 pr-3 sm:pr-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-green-500 focus:border-transparent appearance-none"
                disabled={!!userDistrict}
              >
                <option value="">Select District</option>
                {districts.map((district) => (
                  <option key={district} value={district}>
                    {district}
                  </option>
                ))}
              </select>
              <div className="pointer-events-none absolute inset-y-0 right-0 flex items-center px-2 text-gray-700">
                <svg className="fill-current h-3 w-3 sm:h-4 sm:w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                  <path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z" />
                </svg>
              </div>
            </div>
            {userDistrict && (
              <p className="text-xs text-green-600 mt-1">
                Your assigned district: <strong>{userDistrict}</strong>
              </p>
            )}
          </div>



          <div className="sm:col-span-2 flex justify-end space-x-3 pt-2 sm:pt-4">
            <button
              type="button"
              onClick={onClose}
              className="px-3 sm:px-5 py-2 border border-gray-300 rounded-lg hover:bg-gray-50 font-medium"
              disabled={submitting}
            >
              Cancel
            </button>
            <button
              type="submit"
              disabled={submitting}
              className="px-3 sm:px-5 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 font-medium shadow-sm disabled:opacity-70 flex items-center space-x-2"
            >
              {submitting ? (
                <>
                  <Loader2 className="w-3 sm:w-4 h-3 sm:h-4 animate-spin" />
                  <span>Saving...</span>
                </>
              ) : (
                <span>Save Course</span>
              )}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};

// Edit Course Modal Component
interface EditCourseModalProps {
  isOpen: boolean;
  onClose: () => void;
  onUpdate: (courseId: number, courseData: Partial<CourseType>) => Promise<void>;
  course: CourseType | null;
  districts: string[];
  instructors: any[];
  centers: Center[];
  categories: string[];
  durations: string[];
  updating: boolean;
  userDistrict?: string;
  instructorsError?: boolean;
}

const EditCourseModal: React.FC<EditCourseModalProps> = ({
  isOpen,
  onClose,
  onUpdate,
  course,
  districts,
  instructors,
  centers,
  categories,
  durations,
  updating,
  userDistrict,
  instructorsError
}) => {
  const [formData, setFormData] = useState({
    name: '',
    code: '',
    category: '',
    duration: '',
    description: '',
    district: '',
    center: '',
    instructor: '',
    students: '0',
    schedule: '',
    next_session: ''
  });

  // Filter instructors and centers by selected district
  // Filter instructors and centers by selected district
  // Filter instructors and centers by selected district
  const filteredInstructors = Array.isArray(instructors) ? instructors.filter(instructor => {
    if (!instructor.district) return false;
    if (!formData.district) return false;

    // Check for exact match, or if one contains the other
    const normalize = (s: string) => s.toLowerCase().replace("district", "").trim();
    const d1 = normalize(instructor.district || "");
    const d2 = normalize(formData.district || "");
    return d1 === d2 || d1.includes(d2) || d2.includes(d1);
  }) : [];

  const filteredCenters = Array.isArray(centers) ? centers.filter(center =>
    center.district === formData.district
  ) : [];

  useEffect(() => {
    if (course && isOpen) {
      setFormData({
        name: course.name || '',
        code: course.code || '',
        category: course.category || '',
        duration: course.duration || '',
        description: course.description || '',
        district: course.district || userDistrict || '',
        center: course.center?.toString() || '',
        instructor: course.instructor?.toString() || '',
        students: course.students?.toString() || '0',
        schedule: course.schedule || '',
        next_session: course.next_session || ''
      });
    }
  }, [course, isOpen, userDistrict]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!course) return;

    // Validate required fields
    if (!formData.name.trim() || !formData.code.trim() || !formData.district.trim() || !formData.center.trim()) {
      toast.error('Please fill in all required fields (Name, Code, District, and Center)');
      return;
    }

    try {
      const courseToUpdate = {
        name: formData.name,
        code: formData.code,
        category: formData.category,
        duration: formData.duration,
        description: formData.description,
        district: formData.district,
        center: parseInt(formData.center),
        instructor: formData.instructor ? parseInt(formData.instructor) : null,
        students: parseInt(formData.students) || 0,
        schedule: formData.schedule,
        next_session: formData.next_session
      };
      await onUpdate(course.id, courseToUpdate);
      onClose();
    } catch (error) {
      console.error('Error updating course:', error);
    }
  };

  if (!isOpen || !course) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black bg-opacity-50">
      <div className="bg-white rounded-xl shadow-2xl w-full max-w-lg sm:max-w-3xl p-5 sm:p-8 relative max-h-[90vh] overflow-y-auto">
        <button
          onClick={onClose}
          className="absolute top-3 sm:top-5 right-3 sm:right-5 text-gray-400 hover:text-gray-600"
        >
          <X className="w-5 sm:w-6 h-5 sm:h-6" />
        </button>

        <h2 className="text-xl sm:text-2xl font-bold text-gray-900 mb-6 sm:mb-8">Edit Course</h2>

        <form onSubmit={handleSubmit} className="grid grid-cols-1 sm:grid-cols-2 gap-5 sm:gap-6">
          <div className="sm:col-span-2">
            <label className="block text-sm font-medium text-gray-700 mb-1">
              Course Name <span className="text-red-500">*</span>
            </label>
            <input
              type="text"
              required
              value={formData.name}
              onChange={(e) => setFormData({ ...formData, name: e.target.value })}
              className="w-full px-3 sm:px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-green-500 focus:border-transparent"
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              Course Code <span className="text-red-500">*</span>
            </label>
            <input
              type="text"
              required
              value={formData.code}
              onChange={(e) => setFormData({ ...formData, code: e.target.value.toUpperCase() })}
              className="w-full px-3 sm:px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-green-500 focus:border-transparent"
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              Category
            </label>
            <select
              value={formData.category}
              onChange={(e) => setFormData({ ...formData, category: e.target.value })}
              className="w-full px-3 sm:px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-green-500 focus:border-transparent"
            >
              <option value="">Select Category</option>
              {categories.map((category) => (
                <option key={category} value={category}>{category}</option>
              ))}
            </select>
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              Duration
            </label>
            <select
              value={formData.duration}
              onChange={(e) => setFormData({ ...formData, duration: e.target.value })}
              className="w-full px-3 sm:px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-green-500 focus:border-transparent"
            >
              <option value="">Select Duration</option>
              {durations.map((duration) => (
                <option key={duration} value={duration}>{duration}</option>
              ))}
            </select>
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              <Users className="w-3 sm:w-4 h-3 sm:h-4 inline mr-1" />
              Student Count
            </label>
            <input
              type="number"
              min="0"
              value={formData.students}
              onChange={(e) => setFormData({ ...formData, students: e.target.value })}
              className="w-full px-3 sm:px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-green-500 focus:border-transparent"
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              <Calendar className="w-3 sm:w-4 h-3 sm:h-4 inline mr-1" />
              Schedule
            </label>
            <input
              type="text"
              value={formData.schedule}
              onChange={(e) => setFormData({ ...formData, schedule: e.target.value })}
              className="w-full px-3 sm:px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-green-500 focus:border-transparent"
              placeholder="e.g., Mon-Wed-Fri 9:00-11:00"
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              <Clock className="w-3 sm:w-4 h-3 sm:h-4 inline mr-1" />
              Next Session
            </label>
            <input
              type="text"
              value={formData.next_session}
              onChange={(e) => setFormData({ ...formData, next_session: e.target.value })}
              className="w-full px-3 sm:px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-green-500 focus:border-transparent"
              placeholder="e.g., December 15, 2024"
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              <Building className="w-3 sm:w-4 h-3 sm:h-4 inline mr-1" />
              Center <span className="text-red-500">*</span>
            </label>
            <div className="relative">
              <Building className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 w-3 sm:w-4 h-3 sm:h-4" />
              <select
                required
                value={formData.center}
                onChange={(e) => setFormData({ ...formData, center: e.target.value })}
                className="w-full pl-8 sm:pl-10 pr-3 sm:pr-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-green-500 focus:border-transparent appearance-none"
              >
                <option value="">Select Center</option>
                {filteredCenters.map((center) => (
                  <option key={center.id} value={center.id}>
                    {center.name}
                    {center.location && ` - ${center.location}`}
                  </option>
                ))}
              </select>
            </div>
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              <User className="w-3 sm:w-4 h-3 sm:h-4 inline mr-1" />
              Instructor
            </label>
            <div className="relative">
              <User className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 w-3 sm:w-4 h-3 sm:h-4" />
              <select
                value={formData.instructor}
                onChange={(e) => setFormData({ ...formData, instructor: e.target.value })}
                className="w-full pl-8 sm:pl-10 pr-3 sm:pr-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-green-500 focus:border-transparent appearance-none"
                disabled={instructorsError}
              >
                <option value="">Select Instructor</option>
                {filteredInstructors.map((instructor) => (
                  <option key={instructor.id} value={instructor.id}>
                    {instructor.first_name} {instructor.last_name}
                    {instructor.email && ` (${instructor.email})`}
                  </option>
                ))}
              </select>
            </div>
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              District <span className="text-red-500">*</span>
            </label>
            <div className="relative">
              <MapPin className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 w-3 sm:w-4 h-3 sm:h-4" />
              <select
                required
                value={formData.district}
                onChange={(e) => setFormData({ ...formData, district: e.target.value })}
                className="w-full pl-8 sm:pl-10 pr-3 sm:pr-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-green-500 focus:border-transparent appearance-none"
              >
                <option value="">Select District</option>
                {districts.map((district) => (
                  <option key={district} value={district}>
                    {district}
                  </option>
                ))}
              </select>
            </div>
          </div>



          <div className="sm:col-span-2 flex justify-end space-x-3 pt-2 sm:pt-4">
            <button
              type="button"
              onClick={onClose}
              className="px-3 sm:px-5 py-2 border border-gray-300 rounded-lg hover:bg-gray-50 font-medium"
              disabled={updating}
            >
              Cancel
            </button>
            <button
              type="submit"
              disabled={updating}
              className="px-3 sm:px-5 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 font-medium shadow-sm disabled:opacity-70 flex items-center space-x-2"
            >
              {updating ? (
                <>
                  <Loader2 className="w-3 sm:w-4 h-3 sm:h-4 animate-spin" />
                  <span>Updating...</span>
                </>
              ) : (
                <span>Update Course</span>
              )}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};

// View Course Details Modal Component
interface ViewCourseModalProps {
  isOpen: boolean;
  onClose: () => void;
  course: CourseType | null;
}

const ViewCourseModal: React.FC<ViewCourseModalProps> = ({
  isOpen,
  onClose,
  course
}) => {
  if (!isOpen || !course) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black bg-opacity-50">
      <div className="bg-white rounded-xl shadow-2xl w-full max-w-md sm:max-w-2xl p-4 sm:p-6 relative max-h-[90vh] overflow-y-auto">
        <button
          onClick={onClose}
          className="absolute top-2 sm:top-4 right-2 sm:right-4 text-gray-400 hover:text-gray-600"
        >
          <X className="w-4 sm:w-5 h-4 sm:h-5" />
        </button>

        <h2 className="text-xl sm:text-2xl font-bold text-gray-900 mb-4 sm:mb-6">Course Details</h2>

        <div className="space-y-4 sm:space-y-6">
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 sm:gap-6">
            <div>
              <h3 className="text-base sm:text-lg font-semibold text-gray-900 mb-2">Basic Information</h3>
              <div className="space-y-3 text-xs sm:text-sm">
                <div>
                  <label className="block text-xs sm:text-sm font-medium text-gray-700">Course Name</label>
                  <p className="mt-1 text-gray-900">{course.name}</p>
                </div>
                <div>
                  <label className="block text-xs sm:text-sm font-medium text-gray-700">Course Code</label>
                  <p className="mt-1 text-gray-900 font-mono">{course.code}</p>
                </div>
                <div>
                  <label className="block text-xs sm:text-sm font-medium text-gray-700">Category</label>
                  <p className="mt-1 text-gray-900">{course.category || 'Not specified'}</p>
                </div>
                <div>
                  <label className="block text-xs sm:text-sm font-medium text-gray-700">Duration</label>
                  <p className="mt-1 text-gray-900">{course.duration || 'Not specified'}</p>
                </div>
              </div>
            </div>

            <div>
              <h3 className="text-base sm:text-lg font-semibold text-gray-900 mb-2">Location & Instructor</h3>
              <div className="space-y-3 text-xs sm:text-sm">
                <div>
                  <label className="block text-xs sm:text-sm font-medium text-gray-700">District</label>
                  <p className="mt-1 text-gray-900 flex items-center">
                    <MapPin className="w-3 sm:w-4 h-3 sm:h-4 mr-1 text-gray-400" />
                    {course.district}
                  </p>
                </div>
                <div>
                  <label className="block text-xs sm:text-sm font-medium text-gray-700">Center</label>
                  <p className="mt-1 text-gray-900 flex items-center">
                    <Building className="w-3 sm:w-4 h-3 sm:h-4 mr-1 text-gray-400" />
                    {course.center_details?.name || 'Not assigned'}
                  </p>
                </div>
                <div>
                  <label className="block text-xs sm:text-sm font-medium text-gray-700">Instructor</label>
                  <p className="mt-1 text-gray-900 flex items-center">
                    <User className="w-3 sm:w-4 h-3 sm:h-4 mr-1 text-gray-400" />
                    {course.instructor_details
                      ? `${course.instructor_details.first_name} ${course.instructor_details.last_name}`
                      : 'Not assigned'
                    }
                  </p>
                </div>
                <div>
                  <label className="block text-xs sm:text-sm font-medium text-gray-700">Students</label>
                  <p className="mt-1 text-gray-900 flex items-center">
                    <Users className="w-3 sm:w-4 h-3 sm:h-4 mr-1 text-gray-400" />
                    {course.students} enrolled
                  </p>
                </div>
              </div>
            </div>
          </div>

          {course.schedule && (
            <div>
              <label className="block text-xs sm:text-sm font-medium text-gray-700">Schedule</label>
              <p className="mt-1 text-xs sm:text-sm text-gray-900 flex items-center">
                <Calendar className="w-3 sm:w-4 h-3 sm:h-4 mr-1 text-gray-400" />
                {course.schedule}
              </p>
            </div>
          )}

          {course.next_session && (
            <div>
              <label className="block text-xs sm:text-sm font-medium text-gray-700">Next Session</label>
              <p className="mt-1 text-xs sm:text-sm text-gray-900 flex items-center">
                <Clock className="w-3 sm:w-4 h-3 sm:h-4 mr-1 text-gray-400" />
                {course.next_session}
              </p>
            </div>
          )}

          {course.description && (
            <div>
              <label className="block text-xs sm:text-sm font-medium text-gray-700">Description</label>
              <p className="mt-1 text-xs sm:text-sm text-gray-900">{course.description}</p>
            </div>
          )}

          <div className="grid grid-cols-2 gap-4 pt-4 border-t">
            <div>
              <label className="block text-xs sm:text-sm font-medium text-gray-700">Status</label>
              <span className={`inline-flex mt-1 px-2 py-1 text-xs font-semibold rounded-full ${course.status === 'Approved' ? 'bg-green-100 text-green-800' :
                course.status === 'Pending' ? 'bg-yellow-100 text-yellow-800' :
                  course.status === 'Active' ? 'bg-blue-100 text-blue-800' :
                    'bg-red-100 text-red-800'
                }`}>
                {course.status}
              </span>
            </div>
            <div>
              <label className="block text-xs sm:text-sm font-medium text-gray-700">Priority</label>
              <span className={`inline-flex mt-1 px-2 py-1 text-xs font-semibold rounded-full ${course.priority === 'High' ? 'bg-red-100 text-red-800' :
                course.priority === 'Medium' ? 'bg-yellow-100 text-yellow-800' :
                  'bg-green-100 text-green-800'
                }`}>
                {course.priority}
              </span>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

// Main Training Officer Courses Component
const TrainingOfficerCourses: React.FC = () => {
  const [searchTerm, setSearchTerm] = useState('');
  const [courses, setCourses] = useState<CourseType[]>([]);
  const [districts, setDistricts] = useState<string[]>([]);
  const [instructors, setInstructors] = useState<any[]>([]);
  const [centers, setCenters] = useState<Center[]>([]);
  const [categories, setCategories] = useState<string[]>([]);
  const [durations, setDurations] = useState<string[]>([]);
  const [loading, setLoading] = useState(true);
  const [centersLoading, setCentersLoading] = useState(true);
  const [instructorsLoading, setInstructorsLoading] = useState(true);
  const [instructorsError, setInstructorsError] = useState(false);
  const [submitting, setSubmitting] = useState(false);
  const [updating, setUpdating] = useState(false);
  const [actionLoading, setActionLoading] = useState<number | null>(null);

  // Modal states
  const [isAddModalOpen, setIsAddModalOpen] = useState(false);
  const [isEditModalOpen, setIsEditModalOpen] = useState(false);
  const [isViewModalOpen, setIsViewModalOpen] = useState(false);
  const [selectedCourse, setSelectedCourse] = useState<CourseType | null>(null);

  // Get user info
  const userRole = localStorage.getItem("user_role") || "";
  const userDistrict = localStorage.getItem("user_district") || "";
  const isTrainingOfficer = userRole === 'training_officer';

  useEffect(() => {
    loadCourses();
    loadCenters();
    loadInstructors();
    loadOptions();
  }, []);

  const loadOptions = async () => {
    try {
      const cats = await fetchCourseCategories();
      setCategories(cats);
      const durs = await fetchCourseDurations();
      setDurations(durs);
    } catch (e) {
      console.error("Failed to load options", e);
    }
  };

  const loadCourses = async () => {
    try {
      setLoading(true);
      const coursesData = await fetchCourses();
      if (Array.isArray(coursesData)) {
        setCourses(coursesData);
      } else {
        console.error('Invalid courses data received:', coursesData);
        setCourses([]);
        toast.error('Received invalid data format for courses');
      }
    } catch (error) {
      console.error('Error loading courses:', error);
      toast.error('Failed to load courses');
      setCourses([]);
    } finally {
      setLoading(false);
    }
  };

  const loadCenters = async () => {
    try {
      setCentersLoading(true);
      const centersData = await fetchCenters();

      if (Array.isArray(centersData)) {
        setCenters(centersData);
        // Extract unique districts from centers
        const uniqueDistricts = Array.from(
          new Set(centersData.map(center => center.district).filter(Boolean))
        ) as string[];
        setDistricts(uniqueDistricts.sort());
      } else {
        console.error('Invalid centers data received:', centersData);
        setCenters([]);
        setDistricts([]);
      }
    } catch (error) {
      console.error('Error loading centers:', error);
      setDistricts([]);
      toast.error('Failed to load centers and districts');
    } finally {
      setCentersLoading(false);
    }
  };

  const loadInstructors = async () => {
    try {
      setInstructorsLoading(true);
      setInstructorsError(false);

      try {
        const instructorsData = await fetchInstructors();
        console.log("Loaded Instructors Raw:", instructorsData); // DEBUG LOG
        setInstructors(instructorsData);
      } catch (error) {
        console.error('Error loading from instructors endpoint, trying users endpoint:', error);
        try {
          const usersData = await fetchUsers();
          if (Array.isArray(usersData)) {
            const instructorsData = usersData.filter(user =>
              user.role === 'instructor' && user.district
            );
            setInstructors(instructorsData);
          } else {
            throw new Error('Invalid users data format');
          }
        } catch (fallbackError) {
          console.error('Error loading instructors from users endpoint:', fallbackError);
          setInstructorsError(true);
          setInstructors([]); // No mock data
          toast.error('Failed to load instructors.');
        }
      }
    } catch (error) {
      console.error('Error in loadInstructors:', error);
      setInstructorsError(true);
      setInstructors([]); // No mock data
    } finally {
      setInstructorsLoading(false);
    }
  };

  const handleAddCourse = async (courseData: Partial<CourseType>) => {
    setSubmitting(true);
    try {
      await createCourse(courseData);
      await loadCourses();
      toast.success('Course created successfully!');
    } catch (error: any) {
      console.error('Error creating course:', error);
      const errorMessage = error.response?.data?.name?.[0] ||
        error.response?.data?.code?.[0] ||
        error.response?.data?.detail ||
        'Failed to create course';
      toast.error(errorMessage);
      throw error;
    } finally {
      setSubmitting(false);
    }
  };

  const handleUpdateCourse = async (courseId: number, courseData: Partial<CourseType>) => {
    setUpdating(true);
    try {
      await updateCourse(courseId, courseData);
      await loadCourses();
      toast.success('Course updated successfully!');
    } catch (error: any) {
      console.error('Error updating course:', error);
      const errorMessage = error.response?.data?.name?.[0] ||
        error.response?.data?.code?.[0] ||
        error.response?.data?.detail ||
        'Failed to update course';
      toast.error(errorMessage);
      throw error;
    } finally {
      setUpdating(false);
    }
  };

  const handleDelete = async (id: number) => {
    if (window.confirm('Are you sure you want to delete this course? This action cannot be undone.')) {
      try {
        setActionLoading(id);
        await deleteCourse(id);
        await loadCourses();
        toast.success('Course deleted successfully!');
      } catch (error: any) {
        console.error('Error deleting course:', error);
        const errorMessage = error.response?.data?.detail || 'Failed to delete course';
        toast.error(errorMessage);
      } finally {
        setActionLoading(null);
      }
    }
  };

  const handleViewCourse = (course: CourseType) => {
    setSelectedCourse(course);
    setIsViewModalOpen(true);
  };

  const handleEditCourse = (course: CourseType) => {
    setSelectedCourse(course);
    setIsEditModalOpen(true);
  };

  const filteredCourses = (courses || []).filter(
    (course) =>
      course?.name?.toLowerCase().includes(searchTerm.toLowerCase()) ||
      course?.code?.toLowerCase().includes(searchTerm.toLowerCase()) ||
      (course?.category && course.category.toLowerCase().includes(searchTerm.toLowerCase()))
  );

  const isLoading = loading || centersLoading || instructorsLoading;

  if (isLoading) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="flex items-center space-x-3">
          <Loader2 className="w-6 h-6 animate-spin text-green-600" />
          <span className="text-gray-600">Loading courses...</span>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-50">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        {/* Header */}
        <div className="mb-8">
          <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
            <div>
              <h1 className="text-2xl sm:text-3xl font-bold text-gray-900">My Courses</h1>
              <p className="text-sm sm:text-base text-gray-600 mt-2">Add and manage courses pending approval</p>
              {isTrainingOfficer && userDistrict && (
                <p className="text-xs sm:text-sm text-green-600 mt-1">
                  Managing courses in: <strong>{userDistrict}</strong> district
                </p>
              )}
            </div>
            <button
              onClick={() => setIsAddModalOpen(true)}
              disabled={centersLoading || instructorsLoading}
              className="w-full sm:w-auto bg-green-600 text-white px-4 py-2 rounded-lg hover:bg-green-700 transition-colors flex items-center justify-center space-x-2 disabled:opacity-50 disabled:cursor-not-allowed"
            >
              <Plus className="w-4 h-4" />
              <span>Add Course</span>
            </button>
          </div>
        </div>

        {/* Search + Filters */}
        <div className="mb-6">
          <div className="flex flex-col sm:flex-row gap-4">
            <div className="relative flex-1">
              <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 w-4 h-4" />
              <input
                type="text"
                placeholder="Search courses, codes, or categories..."
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                className="w-full pl-10 pr-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-green-500 focus:border-transparent"
              />
            </div>
            <button className="flex items-center justify-center space-x-2 px-4 py-2 border border-gray-300 rounded-lg hover:bg-gray-50">
              <Filter className="w-4 h-4" />
              <span>Filter</span>
            </button>
          </div>
        </div>

        {/* Courses List - Mobile Cards */}
        <div className="sm:hidden space-y-4 mb-6">
          {filteredCourses.map((course) => (
            <div key={course.id} className="bg-white rounded-lg shadow-md p-4 border border-gray-200">
              <div className="flex justify-between items-start mb-2">
                <div className="flex items-center space-x-3">
                  <div className="w-8 h-8 bg-green-100 rounded-full flex items-center justify-center">
                    <BookOpen className="w-4 h-4 text-green-700" />
                  </div>
                  <div>
                    <div className="text-sm font-medium text-gray-900">{course.name}</div>
                    <div className="text-xs text-gray-500">{course.category}</div>
                  </div>
                </div>
                <span
                  className={`inline-flex px-2 py-1 text-xs font-semibold rounded-full ${course.status === 'Approved' ? 'bg-green-100 text-green-800' :
                    course.status === 'Pending' ? 'bg-yellow-100 text-yellow-800' :
                      course.status === 'Active' ? 'bg-blue-100 text-blue-800' :
                        'bg-red-100 text-red-800'
                    }`}
                >
                  {course.status}
                </span>
              </div>
              <div className="space-y-2 text-xs text-gray-600">
                <div className="flex justify-between">
                  <span>Code:</span>
                  <span className="font-mono">{course.code}</span>
                </div>
                <div className="flex justify-between">
                  <span>Duration:</span>
                  <span>{course.duration || 'Not specified'}</span>
                </div>
                <div className="flex justify-between">
                  <span>Center:</span>
                  <span>{course.center_details?.name || 'Not assigned'}</span>
                </div>
                <div className="flex justify-between">
                  <span>Instructor:</span>
                  <span>
                    {course.instructor_details
                      ? `${course.instructor_details.first_name} ${course.instructor_details.last_name}`
                      : 'Not assigned'
                    }
                  </span>
                </div>
                <div className="flex justify-between">
                  <span>Students:</span>
                  <span>{course.students}</span>
                </div>
                <div className="flex justify-between">
                  <span>District:</span>
                  <span>{course.district}</span>
                </div>
              </div>
              <div className="flex justify-end space-x-2 mt-4">
                <button
                  onClick={() => handleViewCourse(course)}
                  className="text-blue-600 hover:text-blue-900"
                  title="View Details"
                >
                  <Eye className="w-4 h-4" />
                </button>
                <button
                  onClick={() => handleEditCourse(course)}
                  className="text-green-600 hover:text-green-900"
                  title="Edit Course"
                  disabled={course.status !== 'Pending'}
                >
                  <Edit className="w-4 h-4" />
                </button>
                <button
                  onClick={() => handleDelete(course.id)}
                  className="text-red-600 hover:text-red-900"
                  disabled={actionLoading === course.id || course.status !== 'Pending'}
                  title="Delete Course"
                >
                  {actionLoading === course.id ? (
                    <Loader2 className="w-4 h-4 animate-spin" />
                  ) : (
                    <Trash2 className="w-4 h-4" />
                  )}
                </button>
              </div>
            </div>
          ))}
        </div>

        {/* Courses Table - Desktop */}
        <div className="hidden sm:block bg-white rounded-lg shadow-md overflow-hidden border border-gray-200 mb-6">
          <div className="overflow-x-auto">
            <table className="min-w-full divide-y divide-gray-200">
              <thead className="bg-gray-50">
                <tr>
                  <th className="px-6 py-3 text-left text-xs font-semibold text-gray-500 uppercase tracking-wider">
                    Course
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-semibold text-gray-500 uppercase tracking-wider">
                    Code
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-semibold text-gray-500 uppercase tracking-wider">
                    Duration
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-semibold text-gray-500 uppercase tracking-wider">
                    Center
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-semibold text-gray-500 uppercase tracking-wider">
                    Instructor
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-semibold text-gray-500 uppercase tracking-wider">
                    Students
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-semibold text-gray-500 uppercase tracking-wider">
                    Status
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-semibold text-gray-500 uppercase tracking-wider">
                    Actions
                  </th>
                </tr>
              </thead>
              <tbody className="bg-white divide-y divide-gray-200">
                {filteredCourses.map((course) => (
                  <tr key={course.id} className="hover:bg-gray-50">
                    <td className="px-6 py-4 whitespace-nowrap flex items-center space-x-3">
                      <div className="w-8 h-8 bg-green-100 rounded-full flex items-center justify-center">
                        <BookOpen className="w-4 h-4 text-green-700" />
                      </div>
                      <div>
                        <div className="text-sm font-medium text-gray-900">{course.name}</div>
                        {course.category && (
                          <div className="text-xs text-gray-500">{course.category}</div>
                        )}
                        <div className="text-xs text-gray-400 flex items-center mt-1">
                          <MapPin className="w-3 h-3 mr-1" />
                          {course.district}
                        </div>
                      </div>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-600 font-mono">
                      {course.code}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-600">
                      {course.duration || 'Not specified'}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-600">
                      {course.center_details
                        ? course.center_details.name
                        : 'Not assigned'
                      }
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-600">
                      {course.instructor_details
                        ? `${course.instructor_details.first_name} ${course.instructor_details.last_name}`
                        : 'Not assigned'
                      }
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-600">
                      <div className="flex items-center">
                        <Users className="w-4 h-4 mr-1 text-gray-400" />
                        {course.students}
                      </div>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <span
                        className={`inline-flex px-2 py-1 text-xs font-semibold rounded-full ${course.status === 'Approved'
                          ? 'bg-green-100 text-green-800'
                          : course.status === 'Pending'
                            ? 'bg-yellow-100 text-yellow-800'
                            : course.status === 'Active'
                              ? 'bg-blue-100 text-blue-800'
                              : 'bg-red-100 text-red-800'
                          }`}
                      >
                        {course.status}
                      </span>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm font-medium space-x-2">
                      <button
                        onClick={() => handleViewCourse(course)}
                        className="text-blue-600 hover:text-blue-900"
                        title="View Details"
                      >
                        <Eye className="w-4 h-4" />
                      </button>
                      <button
                        onClick={() => handleEditCourse(course)}
                        className="text-green-600 hover:text-green-900"
                        title="Edit Course"
                        disabled={course.status !== 'Pending'}
                      >
                        <Edit className="w-4 h-4" />
                      </button>
                      <button
                        onClick={() => handleDelete(course.id)}
                        className="text-red-600 hover:text-red-900"
                        disabled={actionLoading === course.id || course.status !== 'Pending'}
                        title="Delete Course"
                      >
                        {actionLoading === course.id ? (
                          <Loader2 className="w-4 h-4 animate-spin" />
                        ) : (
                          <Trash2 className="w-4 h-4" />
                        )}
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          {/* Empty state */}
          {filteredCourses.length === 0 && (
            <div className="text-center py-12">
              <BookOpen className="mx-auto h-12 w-12 text-gray-400" />
              <h3 className="mt-2 text-sm font-medium text-gray-900">No courses found</h3>
              <p className="mt-1 text-sm text-gray-500">
                {searchTerm ? 'Try adjusting your search criteria.' : 'Get started by adding your first course.'}
              </p>
            </div>
          )}
        </div>

        {/* Stats Summary */}
        <div className="mt-8 grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-4 sm:gap-6">
          <div className="bg-white rounded-lg shadow-md p-4 sm:p-6 border border-gray-200">
            <div className="text-xl sm:text-2xl font-bold text-green-600">{courses.length}</div>
            <div className="text-xs sm:text-sm text-gray-600">Total Courses</div>
          </div>
          <div className="bg-white rounded-lg shadow-md p-4 sm:p-6 border border-gray-200">
            <div className="text-xl sm:text-2xl font-bold text-yellow-500">
              {courses.filter(c => c.status === 'Pending').length}
            </div>
            <div className="text-xs sm:text-sm text-gray-600">Pending Courses</div>
          </div>
          <div className="bg-white rounded-lg shadow-md p-4 sm:p-6 border border-gray-200">
            <div className="text-xl sm:text-2xl font-bold text-sky-500">
              {courses.filter(c => c.status === 'Approved').length}
            </div>
            <div className="text-xs sm:text-sm text-gray-600">Approved Courses</div>
          </div>
          <div className="bg-white rounded-lg shadow-md p-4 sm:p-6 border border-gray-200">
            <div className="text-xl sm:text-2xl font-bold text-lime-800">
              {courses.reduce((acc, course) => acc + course.students, 0)}
            </div>
            <div className="text-xs sm:text-sm text-gray-600">Total Students</div>
          </div>
        </div>

        {/* Add Course Modal */}
        <AddCourseModal
          isOpen={isAddModalOpen}
          onClose={() => setIsAddModalOpen(false)}
          onSave={handleAddCourse}
          districts={districts}
          instructors={instructors}
          centers={centers}
          categories={categories}
          durations={durations}
          submitting={submitting}
          userDistrict={userDistrict}
          instructorsError={instructorsError}
          existingCourses={courses}
        />

        {/* Edit Course Modal */}
        <EditCourseModal
          isOpen={isEditModalOpen}
          onClose={() => setIsEditModalOpen(false)}
          onUpdate={handleUpdateCourse}
          course={selectedCourse}
          districts={districts}
          instructors={instructors}
          centers={centers}
          categories={categories}
          durations={durations}
          updating={updating}
          userDistrict={userDistrict}
          instructorsError={instructorsError}
        />

        {/* View Course Modal */}
        <ViewCourseModal
          isOpen={isViewModalOpen}
          onClose={() => setIsViewModalOpen(false)}
          course={selectedCourse}
        />
      </div>
    </div>
  );
};

export default TrainingOfficerCourses;