# Generated by Django 5.2.8 on 2025-11-20 08:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_no', models.CharField(blank=True, max_length=20, unique=True)),
                ('full_name_english', models.CharField(max_length=200)),
                ('full_name_sinhala', models.CharField(blank=True, max_length=200)),
                ('name_with_initials', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('nic_id', models.CharField(max_length=20, unique=True)),
                ('address_line', models.TextField(blank=True)),
                ('district', models.CharField(max_length=100)),
                ('divisional_secretariat', models.CharField(max_length=100)),
                ('grama_niladhari_division', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('residence_type', models.CharField(blank=True, max_length=50)),
                ('mobile_no', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('training_received', models.BooleanField(default=False)),
                ('training_provider', models.CharField(blank=True, max_length=200)),
                ('course_vocation_name', models.CharField(blank=True, max_length=200)),
                ('training_duration', models.CharField(blank=True, max_length=100)),
                ('training_nature', models.CharField(choices=[('Initial', 'Initial'), ('Further', 'Further'), ('Re-training', 'Re-training')], default='Initial', max_length=20)),
                ('training_establishment', models.CharField(blank=True, max_length=200)),
                ('training_placement_preference', models.CharField(choices=[('1st', '1st Preference'), ('2nd', '2nd Preference'), ('3rd', '3rd Preference')], default='1st', max_length=3)),
                ('date_of_application', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_students', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EducationalQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=10)),
                ('year', models.IntegerField()),
                ('type', models.CharField(choices=[('OL', 'G.C.E. O/L'), ('AL', 'G.C.E. A/L')], max_length=2)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='students.student')),
            ],
            options={
                'ordering': ['type', 'year', 'subject'],
            },
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['registration_no'], name='students_st_registr_5bb7fe_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['nic_id'], name='students_st_nic_id_736a16_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['district'], name='students_st_distric_88847e_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['created_at'], name='students_st_created_78a19f_idx'),
        ),
    ]
