# Generated by Django 5.2.8 on 2025-11-20 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0004_rename_instructors_center_instructor_count_and_more'),
        ('courses', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrolled_students', to='centers.center'),
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrolled_students', to='courses.course'),
        ),
        migrations.AddField(
            model_name='student',
            name='enrollment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='enrollment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Enrolled', 'Enrolled'), ('Completed', 'Completed'), ('Dropped', 'Dropped')], default='Pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['center'], name='students_st_center__4f2044_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['course'], name='students_st_course__5eee3a_idx'),
        ),
    ]
