# Generated by Django 5.2.8 on 2025-12-12 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_student_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='residence_type',
        ),
        migrations.AddField(
            model_name='student',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=20),
        ),
    ]
