# Generated by Django 5.2.8 on 2025-11-18 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approval',
            name='amount',
        ),
    ]
