# Generated by Django 5.2.8 on 2025-11-18 05:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0002_remove_approval_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='amount',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
