# Generated by Django 5.2.8 on 2025-11-18 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0003_approval_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approval',
            name='amount',
        ),
    ]
