# Generated by Django 5.2.8 on 2025-12-15 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0006_remove_student_residence_type_student_marital_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GraduateStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_status', models.CharField(choices=[('employed', 'Employed'), ('self_employed', 'Self-Employed'), ('unemployed', 'Unemployed'), ('further_education', 'Further Education'), ('seeking_employment', 'Seeking Employment')], default='seeking_employment', max_length=20)),
                ('employment_type', models.CharField(blank=True, choices=[('full_time', 'Full-Time'), ('part_time', 'Part-Time'), ('contract', 'Contract'), ('freelance', 'Freelance'), ('internship', 'Internship')], max_length=20, null=True)),
                ('workplace', models.CharField(blank=True, max_length=200, null=True, verbose_name='Company/Organization')),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('employment_start_date', models.DateField(blank=True, null=True)),
                ('salary_range', models.CharField(blank=True, max_length=50, null=True, verbose_name='Salary Range (LKR)')),
                ('pursuing_higher_education', models.BooleanField(default=False)),
                ('education_level', models.CharField(blank=True, choices=[('diploma', 'Diploma'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('phd', 'PhD'), ('professional_cert', 'Professional Certification'), ('other', 'Other')], max_length=20, null=True)),
                ('institution_name', models.CharField(blank=True, max_length=200, null=True)),
                ('degree_program', models.CharField(blank=True, max_length=200, null=True, verbose_name='Degree/Program')),
                ('enrollment_date', models.DateField(blank=True, null=True)),
                ('expected_completion_date', models.DateField(blank=True, null=True)),
                ('additional_skills', models.TextField(blank=True, null=True, verbose_name='Additional Skills Acquired')),
                ('certifications_obtained', models.TextField(blank=True, null=True, verbose_name='Certifications Obtained')),
                ('graduation_date', models.DateField(verbose_name='Date of Graduation')),
                ('follow_up_date', models.DateField(blank=True, null=True, verbose_name='Next Follow-up Date')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('employment_info_completed', models.BooleanField(default=False)),
                ('education_info_completed', models.BooleanField(default=False)),
                ('contact_allowed', models.BooleanField(default=True, verbose_name='Allow contact for follow-up')),
                ('success_story', models.TextField(blank=True, null=True, verbose_name='Success Story/Testimonial')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_graduates', to=settings.AUTH_USER_MODEL)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='graduate_info', to='students.student', verbose_name='Original Student')),
            ],
            options={
                'verbose_name': 'Graduate Student',
                'verbose_name_plural': 'Graduate Students',
                'ordering': ['-graduation_date', 'student__full_name_english'],
            },
        ),
        migrations.CreateModel(
            name='GraduateFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_up_type', models.CharField(choices=[('phone', 'Phone Call'), ('email', 'Email'), ('visit', 'Site Visit'), ('social_media', 'Social Media'), ('event', 'Event Meeting')], default='phone', max_length=20)),
                ('scheduled_date', models.DateField()),
                ('actual_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('rescheduled', 'Rescheduled'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('outcome', models.TextField(blank=True, null=True, verbose_name='Follow-up Outcome')),
                ('next_action', models.TextField(blank=True, null=True)),
                ('next_follow_up_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conducted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_follow_ups', to=settings.AUTH_USER_MODEL)),
                ('graduate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='graduated_students.graduatestudent')),
            ],
            options={
                'verbose_name': 'Follow-up Activity',
                'verbose_name_plural': 'Follow-up Activities',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='GraduateAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_type', models.CharField(choices=[('promotion', 'Job Promotion'), ('certification', 'Professional Certification'), ('degree_completion', 'Degree Completion'), ('award', 'Award/Recognition'), ('startup', 'Startup Founded'), ('publication', 'Publication'), ('project', 'Notable Project')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_achieved', models.DateField()),
                ('supporting_document', models.FileField(blank=True, null=True, upload_to='graduate_achievements/')),
                ('verified', models.BooleanField(default=False)),
                ('verified_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_achievements', to=settings.AUTH_USER_MODEL)),
                ('graduate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='graduated_students.graduatestudent')),
            ],
            options={
                'verbose_name': 'Graduate Achievement',
                'verbose_name_plural': 'Graduate Achievements',
                'ordering': ['-date_achieved'],
            },
        ),
        migrations.AddIndex(
            model_name='graduatestudent',
            index=models.Index(fields=['employment_status'], name='graduated_s_employm_50b95a_idx'),
        ),
        migrations.AddIndex(
            model_name='graduatestudent',
            index=models.Index(fields=['pursuing_higher_education'], name='graduated_s_pursuin_c36140_idx'),
        ),
        migrations.AddIndex(
            model_name='graduatestudent',
            index=models.Index(fields=['graduation_date'], name='graduated_s_graduat_3f1ee7_idx'),
        ),
        migrations.AddIndex(
            model_name='graduatestudent',
            index=models.Index(fields=['follow_up_date'], name='graduated_s_follow__7a404c_idx'),
        ),
    ]
