# Generated by Django 5.2.8 on 2025-12-15 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduated_students', '0002_graduatestudent_current_status_and_more'),
        ('students', '0006_remove_student_residence_type_student_marital_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graduatefollowup',
            name='conducted_by',
        ),
        migrations.RemoveField(
            model_name='graduatefollowup',
            name='graduate',
        ),
        migrations.RemoveField(
            model_name='graduatestudent',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='graduatestudent',
            name='student',
        ),
        migrations.CreateModel(
            name='GraduatedStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduate_education', models.TextField(blank=True, help_text='Higher education details after graduation (e.g., BSc in Computer Science - University of Colombo)', null=True)),
                ('workplace', models.CharField(blank=True, help_text='Current workplace or company name', max_length=200, null=True)),
                ('job_description', models.TextField(blank=True, help_text='Job role and responsibilities', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(help_text='Reference to the student who graduated', on_delete=django.db.models.deletion.CASCADE, related_name='graduation_info', to='students.student')),
            ],
            options={
                'verbose_name': 'Graduated Student',
                'verbose_name_plural': 'Graduated Students',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='GraduateAchievement',
        ),
        migrations.DeleteModel(
            name='GraduateFollowUp',
        ),
        migrations.DeleteModel(
            name='GraduateStudent',
        ),
        migrations.AddIndex(
            model_name='graduatedstudent',
            index=models.Index(fields=['student'], name='graduated_s_student_6316ea_idx'),
        ),
        migrations.AddIndex(
            model_name='graduatedstudent',
            index=models.Index(fields=['created_at'], name='graduated_s_created_e2b7e5_idx'),
        ),
    ]
