# Generated by Django 5.2.8 on 2025-11-20 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_centers', models.IntegerField()),
                ('active_students', models.IntegerField()),
                ('total_instructors', models.IntegerField()),
                ('completion_rate', models.FloatField()),
                ('snapshot_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'overview_dashboard_snapshot',
            },
        ),
    ]
