# Generated by Django 5.2.8 on 2025-11-18 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Equipment Request', 'Equipment Request'), ('Staff Recruitment', 'Staff Recruitment'), ('Course Addition', 'Course Addition'), ('Infrastructure', 'Infrastructure'), ('Training Materials', 'Training Materials')], max_length=50)),
                ('center', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('amount', models.CharField(max_length=50)),
                ('date_requested', models.DateField(auto_now_add=True)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Under Review', 'Under Review')], default='Pending', max_length=20)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals_requested', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
