# Generated by Django 5.2.8 on 2025-12-15 06:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduated_students', '0001_initial'),
        ('students', '0006_remove_student_residence_type_student_marital_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='graduatestudent',
            name='current_status',
            field=models.CharField(blank=True, editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='graduatestudent',
            name='is_complete',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddIndex(
            model_name='graduatestudent',
            index=models.Index(fields=['is_complete'], name='graduated_s_is_comp_cf0190_idx'),
        ),
    ]
