# Generated by Django 5.2.8 on 2025-12-01 08:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0004_rename_instructors_center_instructor_count_and_more'),
        ('courses', '0002_course_center'),
        ('students', '0002_student_center_student_course_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_code', models.CharField(help_text='Year in YY format (e.g., 24 for 2024)', max_length=4, unique=True)),
                ('description', models.CharField(help_text='e.g., 2024 Batch', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Batch Year',
                'verbose_name_plural': 'Batch Years',
                'ordering': ['-year_code'],
            },
        ),
        migrations.CreateModel(
            name='CourseCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('course_code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Course Code',
                'verbose_name_plural': 'Course Codes',
                'ordering': ['course_code'],
            },
        ),
        migrations.CreateModel(
            name='DistrictCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=100, unique=True)),
                ('district_code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'District Code',
                'verbose_name_plural': 'District Codes',
                'ordering': ['district_name'],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='batch_year',
            field=models.CharField(blank=True, editable=False, max_length=4),
        ),
        migrations.AddField(
            model_name='student',
            name='course_code',
            field=models.CharField(blank=True, editable=False, max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='district_code',
            field=models.CharField(blank=True, editable=False, max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='registration_year',
            field=models.CharField(blank=True, editable=False, max_length=4),
        ),
        migrations.AddField(
            model_name='student',
            name='student_number',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='registration_no',
            field=models.CharField(blank=True, editable=False, max_length=50, unique=True),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['district_code'], name='students_st_distric_61a3a7_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['course_code'], name='students_st_course__211df6_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['batch_year'], name='students_st_batch_y_88833e_idx'),
        ),
    ]
