# Generated by Django 5.2.8 on 2025-12-01 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0004_rename_instructors_center_instructor_count_and_more'),
        ('courses', '0002_course_center'),
        ('students', '0003_batchyear_coursecode_districtcode_student_batch_year_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_code', models.CharField(help_text='Batch code in 2-digit format (e.g., 01 for 1st batch)', max_length=2, unique=True)),
                ('batch_name', models.CharField(help_text='e.g., 1st Batch, 2nd Batch, etc.', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=1, help_text='Order in which batches appear in dropdowns')),
            ],
            options={
                'verbose_name': 'Batch',
                'verbose_name_plural': 'Batches',
                'ordering': ['display_order', 'batch_code'],
            },
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='students_st_batch_y_88833e_idx',
        ),
        migrations.AlterField(
            model_name='student',
            name='batch_year',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='student',
            name='course_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='district_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='registration_no',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='registration_year',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='students.batch'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['batch'], name='students_st_batch_i_c8b64c_idx'),
        ),
    ]
