# Generated by Django 5.2.8 on 2025-12-09 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_batch_remove_student_students_st_batch_y_88833e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Student profile photo', null=True, upload_to='student_photos/'),
        ),
    ]
