# Generated by Django 5.2.8 on 2025-12-12 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_coursecategory_courseduration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseduration',
            options={'ordering': ['order', 'duration']},
        ),
        migrations.AddField(
            model_name='courseduration',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)'),
        ),
    ]
