# Generated by Django 5.2.8 on 2025-11-18 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('district_manager', 'District Manager'), ('training_officer', 'Training Officer'), ('data_entry', 'Data Entry')], default='data_entry', max_length=20),
        ),
    ]
