# Generated by Django 5.2.8 on 2025-11-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('district_manager', 'District Manager'), ('training_officer', 'Training Officer'), ('data_entry', 'Data Entry'), ('instructor', 'Instructor')], default='data_entry', max_length=20),
        ),
    ]
