# Generated by Django 5.2.8 on 2025-12-01 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_district_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined']},
        ),
        migrations.AddField(
            model_name='user',
            name='epf_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('district_manager', 'District Manager'), ('training_officer', 'Training Officer'), ('data_entry', 'Data Entry'), ('instructor', 'Instructor'), ('staff', 'Staff')], default='data_entry', max_length=20),
        ),
    ]
