# Generated by Django 5.2.8 on 2025-12-01 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_options_user_epf_no_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('district_manager', 'District Manager'), ('training_officer', 'Training Officer'), ('data_entry', 'Data Entry'), ('instructor', 'Instructor')], default='data_entry', max_length=20),
        ),
    ]
