# Generated by Django 5.2.8 on 2025-12-02 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_options_remove_user_epf_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='epf_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='EPF Number'),
        ),
    ]
