# Generated by Django 5.2.8 on 2025-12-16 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='system_type',
            field=models.CharField(choices=[('CBT', 'CBT'), ('NTT', 'NTT')], default='CBT', max_length=10, verbose_name='System Type'),
        ),
    ]
