# Generated by Django 5.2.8 on 2025-12-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_user_system_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('district_manager', 'District Manager'), ('training_officer', 'Training Officer'), ('data_entry', 'Data Entry'), ('instructor', 'Instructor'), ('ntt_admin', 'Admin'), ('ntt_data_entry', 'Data Entry')], default='data_entry', max_length=20),
        ),
    ]
