# Generated by Django 5.2.8 on 2025-11-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0002_center_instructors_center_manager_center_performance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
