# Generated by Django 5.2.8 on 2025-11-20 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0003_center_district'),
    ]

    operations = [
        migrations.RenameField(
            model_name='center',
            old_name='instructors',
            new_name='instructor_count',
        ),
        migrations.RenameField(
            model_name='center',
            old_name='students',
            new_name='student_count',
        ),
    ]
